/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import DAO.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author K
 */
public class DatosPacientesRCP extends javax.swing.JFrame {
    Conexion cn= new Conexion();
    Connection con=cn.getConexion();

    public DatosPacientesRCP() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtxtNombres = new javax.swing.JTextField();
        jtxtApellidos = new javax.swing.JTextField();
        jtxtSexo = new javax.swing.JTextField();
        jtxtDni = new javax.swing.JTextField();
        jtxtRaza = new javax.swing.JTextField();
        jtxtLugarN = new javax.swing.JTextField();
        jtxtLugarR = new javax.swing.JTextField();
        jFecha = new com.toedter.calendar.JDateChooser();
        jtxtMotivo = new javax.swing.JTextField();
        jFechaN = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "HISTORIA DE PACIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("NOMBRES");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 80, 40));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("APELLIDOS");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 80, 40));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("SEXO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 80, 40));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("REGISTRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 610, 160, 50));

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("MODIFICAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 610, 160, 50));

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setText("ELIMINAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 610, 160, 50));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("FECHA DE NACIMIENTO");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 170, 30));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("DNI");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 100, 30));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("RAZA");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 50, 30));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("MOTIVO DE CONSULTA");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 520, 160, 30));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("FECHA");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, 50, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("LUGAR DE NACIMIENTO");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, 30));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("LUGAR DE RESIDENCIA");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, -1, 30));
        jPanel1.add(jtxtNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, 200, 40));
        jPanel1.add(jtxtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 200, 40));
        jPanel1.add(jtxtSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 200, 40));
        jPanel1.add(jtxtDni, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 200, 40));
        jPanel1.add(jtxtRaza, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 200, 40));
        jPanel1.add(jtxtLugarN, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 340, 200, 40));
        jPanel1.add(jtxtLugarR, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, 200, 40));

        jFecha.setDateFormatString("yyyy/MM/dd");
        jPanel1.add(jFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 450, 200, 40));
        jPanel1.add(jtxtMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 200, 40));

        jFechaN.setDateFormatString("yyyy/MM/dd");
        jPanel1.add(jFechaN, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 200, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 680));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRO DE HISTORIA DE PACIENTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 690, 550));
        jPanel2.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 210, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 710, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        eliminarRegistros();
        limpiarDatos();
        mostrarDatos();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        registrar();
        limpiarDatos();
        mostrarDatos();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        actualizarDatos();
        limpiarDatos();
        mostrarDatos();
    }//GEN-LAST:event_jButton2ActionPerformed

    public void registrar(){
        Conexion cc=new Conexion();
        Connection cn=cc.getConexion();
        try{
           String sql= "INSERT INTO historia_paciente (nombres_historiapac,apellidos_historiapac,sexo_historiapac,fechanacimiento_historiapac,dni_historiapac,raza_historiapac,lugarnac_historiapac,lugaresi_historiapac,fecha_historiapac,especialidad_historiapac) VALUES(?,?,?,?,?,?,?,?,?,?)"; 
           PreparedStatement pst=cn.prepareStatement(sql);
           pst.setString(1, jtxtNombres.getText());
           pst.setString(2, jtxtApellidos.getText());
           pst.setString(3, jtxtSexo.getText());
           pst.setString(4, ((JTextField)jFechaN.getDateEditor().getUiComponent()).getText());
           pst.setString(5, jtxtDni.getText());
           pst.setString(6, jtxtRaza.getText());
           pst.setString(7, jtxtLugarN.getText());
           pst.setString(8, jtxtLugarR.getText());
           pst.setString(9, ((JTextField)jFecha.getDateEditor().getUiComponent()).getText());
           pst.setString(10, jtxtMotivo.getText());
           pst.execute();
           JOptionPane.showMessageDialog(null, "Registro Exitoso");
        }catch (Exception e){
           JOptionPane.showMessageDialog(null, "Vaya... hay un error" + e.getMessage()); 
        }
    }
    
    public void actualizarDatos(){
        try{
            String sql=" update historia_paciente set nombres_historiapac=?,apellidos_historiapac=?,sexo_historiapac=?,fechanacimiento_historiapac=?,dni_historiapac=?,raza_historiapac=?,lugarnac_historiapac=?,lugaresi_historiapac=?,fecha_historiapac=?,especialidad_historiapac=? where id_historiapac=? ";
            int filaseleccionado=jTable1.getSelectedRow();
            String dao=(String)jTable1.getValueAt(filaseleccionado, 0);
            PreparedStatement pst=con.prepareStatement(sql);
            
            pst.setString(1, jtxtNombres.getText());
            pst.setString(2, jtxtApellidos.getText());
            pst.setString(3, jtxtSexo.getText());
            pst.setString(4, ((JTextField)jFechaN.getDateEditor().getUiComponent()).getText());
            pst.setString(5, jtxtDni.getText());
            pst.setString(6, jtxtRaza.getText());
            pst.setString(7, jtxtLugarN.getText());
            pst.setString(8, jtxtLugarR.getText());
            pst.setString(9, ((JTextField)jFecha.getDateEditor().getUiComponent()).getText());
            pst.setString(10, jtxtMotivo.getText());
            pst.setString(11, dao);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Registrado Actualizado");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error al Actualizar");
        }
    }
    
    public void eliminarRegistros(){
        int filaSeleccionada=jTable1.getSelectedRow();
        try{
            String sql="delete from historia_paciente where id_historiapac="+jTable1.getValueAt(filaSeleccionada, 0);
            Statement st=con.createStatement();
            int n=st.executeUpdate(sql);
            if(n>=0){
                JOptionPane.showMessageDialog(null,"Registro Eliminado");
            } 
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error al eliminar Registro");
        }
    }
    
    public void limpiarDatos(){
        jtxtNombres.setText("");
        jtxtApellidos.setText("");
        jtxtSexo.setText("");
        jFechaN.setToolTipText("");//fecha
        jtxtDni.setText("");
        jtxtRaza.setText("");
        jtxtLugarN.setText("");
        jtxtLugarR.setText("");        
        jFecha.setToolTipText("");//fecha
        jtxtMotivo.setText("");                
    }
    
    public void mostrarDatos(){
        String[] titulos={"Id","Nombre","Apellidos","Sexo","Fecha Naciemiento","DNI","Raza","Lugar Naciemiento","Lugar Residencia","Fecha","Motivo"};
        String[] registros=new String[11];
        
        DefaultTableModel model=new DefaultTableModel(null,titulos);
        
        String sql="select * from historia_paciente";
        
        try{
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
                registros[0]=rs.getString("id_historiapac");//id
                registros[1]=rs.getString("nombres_historiapac");
                registros[2]=rs.getString("apellidos_historiapac");
                registros[3]=rs.getString("sexo_historiapac");
                registros[4]=rs.getString("fechanacimiento_historiapac");
                registros[5]=rs.getString("dni_historiapac");
                registros[6]=rs.getString("raza_historiapac");
                registros[7]=rs.getString("lugarnac_historiapac");
                registros[8]=rs.getString("lugaresi_historiapac");
                registros[9]=rs.getString("fecha_historiapac");
                registros[10]=rs.getString("especialidad_historiapac");
                
                model.addRow(registros);
            }
            jTable1.setModel(model);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error al mostrar datos");
        }
    }
    public void filtrarDatos(String valor){
        String[] titulos={"Id","Codigo","Fecha","DNI","Especialidad","Monto"};
        String[] registros=new String[6];
        
        DefaultTableModel model=new DefaultTableModel(null,titulos);
        
        String sql="select * from historia_paciente where dni_historiapac like '%"+valor+"%'";
        
        try{
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
                registros[0]=rs.getString("id_historiapac");//id
                registros[1]=rs.getString("nombres_historiapac");
                registros[2]=rs.getString("apellidos_historiapac");
                registros[3]=rs.getString("sexo_historiapac");
                registros[4]=rs.getString("fechanacimiento_historiapac");
                registros[5]=rs.getString("dni_historiapac");
                registros[6]=rs.getString("raza_historiapac");
                registros[7]=rs.getString("lugarnac_historiapac");
                registros[8]=rs.getString("lugaresi_historiapac");
                registros[9]=rs.getString("fecha_historiapac");
                registros[10]=rs.getString("especialidad_historiapac");
                
                model.addRow(registros);
            }
            jTable1.setModel(model);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error al mostrar datos");
        }
    }
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DatosPacientesRCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DatosPacientesRCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DatosPacientesRCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DatosPacientesRCP.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DatosPacientesRCP().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jFecha;
    private com.toedter.calendar.JDateChooser jFechaN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jtxtApellidos;
    private javax.swing.JTextField jtxtDni;
    private javax.swing.JTextField jtxtLugarN;
    private javax.swing.JTextField jtxtLugarR;
    private javax.swing.JTextField jtxtMotivo;
    private javax.swing.JTextField jtxtNombres;
    private javax.swing.JTextField jtxtRaza;
    private javax.swing.JTextField jtxtSexo;
    // End of variables declaration//GEN-END:variables
}
