/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;



import Control.ControladorForma1;
import Principal.Inicio;
import static Principal.Inicio.jPacientes;


import static Principal.Inicio.form1;
import Vistas.Forma1;


public class Iniciar extends javax.swing.JFrame {

    public static login_pacientes loginpa;
    public static login_medico loginme;
    public static jfrmRegistrar_user_pacie registrarpa;
    public static jfrmRegistrar_user_medic registrarme;  
    public static jfrm_lista_medico lista;
    public static LoginRecepcion loginrcp;
    public static RegistrarRecepcion registrarrcp;
    public Iniciar() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbtnRegistrarPaciente = new javax.swing.JButton();
        jbtnCerrarInicio = new javax.swing.JButton();
        jbtnLoginPaciente = new javax.swing.JButton();
        jbtnPagoPaciente = new javax.swing.JButton();
        jbtnRegistrarMedico = new javax.swing.JButton();
        jbtnIngresarMedico = new javax.swing.JButton();
        jbtnRegistrarUsuarioRCP = new javax.swing.JButton();
        jbtnIngresarUsuarioRCP = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("BIENVENIDO A FORD DENTAL");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 290, 100));

        jbtnRegistrarPaciente.setBackground(new java.awt.Color(255, 255, 255));
        jbtnRegistrarPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imag6.jpeg"))); // NOI18N
        jbtnRegistrarPaciente.setText("REGISTRAR USUARIO PACIENTE");
        jbtnRegistrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistrarPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnRegistrarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 280, 60));

        jbtnCerrarInicio.setBackground(new java.awt.Color(255, 255, 255));
        jbtnCerrarInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imag2.jpeg"))); // NOI18N
        jbtnCerrarInicio.setText("CERRAR");
        jbtnCerrarInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCerrarInicioActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnCerrarInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 180, -1));

        jbtnLoginPaciente.setBackground(new java.awt.Color(255, 255, 255));
        jbtnLoginPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imag6.jpeg"))); // NOI18N
        jbtnLoginPaciente.setText("INGRESAR USUARIO PACIENTE");
        jbtnLoginPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnLoginPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnLoginPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 280, 60));

        jbtnPagoPaciente.setBackground(new java.awt.Color(255, 255, 255));
        jbtnPagoPaciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imag3.jpeg"))); // NOI18N
        jbtnPagoPaciente.setText("LISTA MEDICOS");
        jbtnPagoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnPagoPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnPagoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, 730, 70));

        jbtnRegistrarMedico.setBackground(new java.awt.Color(255, 255, 255));
        jbtnRegistrarMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imag1.jpeg"))); // NOI18N
        jbtnRegistrarMedico.setText("REGISTRAR USUARIO MEDICO");
        jbtnRegistrarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistrarMedicoActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnRegistrarMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 280, 60));

        jbtnIngresarMedico.setBackground(new java.awt.Color(255, 255, 255));
        jbtnIngresarMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imag1.jpeg"))); // NOI18N
        jbtnIngresarMedico.setText("INGRESAR USUARIO MEDICO");
        jbtnIngresarMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIngresarMedicoActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnIngresarMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 280, 60));

        jbtnRegistrarUsuarioRCP.setBackground(new java.awt.Color(255, 255, 255));
        jbtnRegistrarUsuarioRCP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imag7.jpeg"))); // NOI18N
        jbtnRegistrarUsuarioRCP.setText("REGISTRAR USUARIO RECEPCION");
        jbtnRegistrarUsuarioRCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRegistrarUsuarioRCPActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnRegistrarUsuarioRCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, 290, 60));

        jbtnIngresarUsuarioRCP.setBackground(new java.awt.Color(255, 255, 255));
        jbtnIngresarUsuarioRCP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imag7.jpeg"))); // NOI18N
        jbtnIngresarUsuarioRCP.setText("INGRESAR USUARIO RECEPCION");
        jbtnIngresarUsuarioRCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIngresarUsuarioRCPActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnIngresarUsuarioRCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 250, 290, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imag8.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, 240, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 519, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnCerrarInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCerrarInicioActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
    }//GEN-LAST:event_jbtnCerrarInicioActionPerformed

    private void jbtnRegistrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistrarPacienteActionPerformed
        if(registrarpa == null){
            registrarpa = new jfrmRegistrar_user_pacie();
            registrarpa.setVisible(true);
        }
    }//GEN-LAST:event_jbtnRegistrarPacienteActionPerformed

    private void jbtnLoginPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnLoginPacienteActionPerformed
        if(loginpa == null){
            loginpa = new login_pacientes();
            loginpa.setVisible(true);
        }
    }//GEN-LAST:event_jbtnLoginPacienteActionPerformed

    private void jbtnPagoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnPagoPacienteActionPerformed
        /*form = new Formulario();
        form.setVisible(true);
        form.setLocationRelativeTo(form);
        contfrm=new ControlFormulario(form);*/
        if(lista == null){
            lista = new jfrm_lista_medico();
            lista.setVisible(true);
       } 
    }//GEN-LAST:event_jbtnPagoPacienteActionPerformed

    private void jbtnRegistrarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistrarMedicoActionPerformed
        if(registrarme == null){
            registrarme = new jfrmRegistrar_user_medic();
            registrarme.setVisible(true);
    }//GEN-LAST:event_jbtnRegistrarMedicoActionPerformed
    }
    private void jbtnIngresarMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIngresarMedicoActionPerformed
            if(loginme == null){
            loginme = new login_medico();
            loginme.setVisible(true);
        }
    }//GEN-LAST:event_jbtnIngresarMedicoActionPerformed

    private void jbtnRegistrarUsuarioRCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRegistrarUsuarioRCPActionPerformed
         if(registrarrcp == null){
            registrarrcp = new RegistrarRecepcion();
            registrarrcp.setVisible(true);
        }
    }//GEN-LAST:event_jbtnRegistrarUsuarioRCPActionPerformed

    private void jbtnIngresarUsuarioRCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIngresarUsuarioRCPActionPerformed
        if(loginrcp == null){
            loginrcp = new LoginRecepcion();
            loginrcp.setVisible(true);
        }
    }//GEN-LAST:event_jbtnIngresarUsuarioRCPActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Iniciar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Iniciar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnCerrarInicio;
    private javax.swing.JButton jbtnIngresarMedico;
    private javax.swing.JButton jbtnIngresarUsuarioRCP;
    private javax.swing.JButton jbtnLoginPaciente;
    private javax.swing.JButton jbtnPagoPaciente;
    private javax.swing.JButton jbtnRegistrarMedico;
    private javax.swing.JButton jbtnRegistrarPaciente;
    private javax.swing.JButton jbtnRegistrarUsuarioRCP;
    // End of variables declaration//GEN-END:variables
}
