/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import DAO.conexion_medico;
import Modelos.Doctor;
import Modelos.forddental_medico;
import Modelos.hs;
import Modelos.sqlforddental_me;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author aless
 */
public class jfrmRegistrar_user_medic extends javax.swing.JFrame {

    conexion_medico enlace = new conexion_medico();
    Connection conect = enlace.conexion_medico(); 
    private Doctor doc;
    private String id;
    private jfrm_lista_medico lista;
    
    
    public jfrmRegistrar_user_medic() {
        initComponents();
    }
    
    void lecturadatos(){        
                doc = new Doctor();//creamos un objeto
                doc.setUsuario_medico(jtxtUsuarioMedico.getText());//recuperamos el codigo
                doc.setContraseña_medico(jtxtContraseñaMedico.getText());//recuperamos el nombre
                doc.setNombres_medico(jtxtNombresMedico.getText());//recuperamos la direccion
                doc.setApellidos_medico(jtxtApellidosMedico.getText());//recuperamos la carrera
                doc.setSede(jtxtSedeMedico.getText());//recuperamos la carrera
                doc.setCelular_medico(jtxtCelularMedico.getText());//recuperamos la carrera
                doc.setEspecialidad_medico(jtxtEspecializacionMedico.getText());//recuperamos la carrera
                doc.setCorreo_medico(jtxtCorreoMedico.getText());//recuperamos la carrera
        }     
       
       public void ActualizarDoc(Doctor nuevodoc) {
        try{
            PreparedStatement consulta;
            consulta = conect.prepareStatement("update usuario_medico set contraseña_medico=?, nombres_medico=?, apellidos_medico=?, sede=?, celular_medico=?, especialidad_medico=?, correo_medico=? where usuario_medico=?;");
                     
            consulta.setString(1, nuevodoc.getContraseña_medico());
            consulta.setString(2, nuevodoc.getNombres_medico());
            consulta.setString(3, nuevodoc.getApellidos_medico());
            consulta.setString(4, nuevodoc.getSede());
            consulta.setString(5, nuevodoc.getCelular_medico());
            consulta.setString(6, nuevodoc.getEspecialidad_medico());
            consulta.setString(7, nuevodoc.getCorreo_medico());
            consulta.setString(8, nuevodoc.getUsuario_medico());
            consulta.executeUpdate();//actualizar la comsult y la ejecucion
            conect.close();//cerramos la conexion.
            JOptionPane.showMessageDialog(null,"Datos actualizados correctamente");
            jtxtUsuarioMedico.setText("");
                jtxtContraseñaMedico.setText("");
                jtxtReContraseñaMedico.setText("");
                jtxtNombresMedico.setText("");
                jtxtApellidosMedico.setText("");
                jtxtSedeMedico.setText("");
                jtxtCelularMedico.setText("");
                jtxtEspecializacionMedico.setText("");
                jtxtCorreoMedico.setText(""); 
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"ERROR AL ACTULIZAR REGISTRO"+e);
        } 
        
        
    }
       
       public void EliminarDoc(String id) {
       try{
           PreparedStatement consulta;
           //preparamos la consulta con la ? que vamos a actualizar con el codigo
           consulta =  conect.prepareStatement("delete from usuario_medico where usuario_medico=?;");
           consulta.setString(1,id); //actualizamos el parametro con el codigo
           consulta.executeUpdate(); //actualizamos y ejecutamos la consulta.
           conect.close();//cerramos la conexion.
           JOptionPane.showMessageDialog(null,"Registro Eliminado...");
           jtxtUsuarioMedico.setText("");
                jtxtContraseñaMedico.setText("");
                jtxtReContraseñaMedico.setText("");
                jtxtNombresMedico.setText("");
                jtxtApellidosMedico.setText("");
                jtxtSedeMedico.setText("");
                jtxtCelularMedico.setText("");
                jtxtEspecializacionMedico.setText("");
                jtxtCorreoMedico.setText(""); 
       } catch(Exception ex){
           JOptionPane.showMessageDialog(null,"ERROR al eliminar registro..."+ex);
       }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtUsuarioMedico = new javax.swing.JTextField();
        jtxtContraseñaMedico = new javax.swing.JPasswordField();
        jtxtReContraseñaMedico = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtxtNombresMedico = new javax.swing.JTextField();
        jtxtApellidosMedico = new javax.swing.JTextField();
        jtxtSedeMedico = new javax.swing.JTextField();
        jtxtCelularMedico = new javax.swing.JTextField();
        jtxtEspecializacionMedico = new javax.swing.JTextField();
        jtxtCorreoMedico = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jbtnCrearMedico = new javax.swing.JButton();
        jbtxBuscar = new javax.swing.JButton();
        jbtxActualizar = new javax.swing.JButton();
        jbtxEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRAR MEDICO");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 39, -1, 29));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("USUARIO:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 94, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CONTRASEÑA:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(73, 131, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("<html>REPETIR CONTRASEÑA:</html>");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 68, -1));
        getContentPane().add(jtxtUsuarioMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 91, 153, -1));
        getContentPane().add(jtxtContraseñaMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 128, 153, -1));

        jtxtReContraseñaMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtReContraseñaMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtReContraseñaMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 153, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("NOMBRES:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("APELLIDOS:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("SEDE:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 280, -1, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CELULAR:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("ESPECIALIZACION:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, -1, -1));

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("CORREO:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        jtxtNombresMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNombresMedicoActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtNombresMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 153, -1));
        getContentPane().add(jtxtApellidosMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, 153, -1));
        getContentPane().add(jtxtSedeMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 153, -1));
        getContentPane().add(jtxtCelularMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 153, -1));
        getContentPane().add(jtxtEspecializacionMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 350, 156, -1));
        getContentPane().add(jtxtCorreoMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 156, -1));

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbtnCrearMedico.setBackground(new java.awt.Color(255, 255, 255));
        jbtnCrearMedico.setText("CREAR");
        jbtnCrearMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCrearMedicoActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnCrearMedico, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 120, 30));

        jbtxBuscar.setText("BUSCAR");
        jbtxBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtxBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtxBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 430, 120, 30));

        jbtxActualizar.setText("ACTUALIZAR");
        jbtxActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtxActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtxActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 480, 120, 30));

        jbtxEliminar.setText("ELIMINAR");
        jbtxEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtxEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtxEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 480, 120, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtNombresMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNombresMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombresMedicoActionPerformed

    private void jtxtReContraseñaMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtReContraseñaMedicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtReContraseñaMedicoActionPerformed

    private void jbtnCrearMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCrearMedicoActionPerformed
                
        String contrme = new String(jtxtContraseñaMedico.getPassword());
        String contrconfme = new String(jtxtReContraseñaMedico.getPassword());
        
        if (jtxtUsuarioMedico.getText().equals("") || contrme.equals("") || contrconfme.equals("") || 
                jtxtNombresMedico.equals("") || jtxtApellidosMedico.equals("") || jtxtSedeMedico.equals("") || jtxtCelularMedico.equals("") || 
                jtxtEspecializacionMedico.equals("") || jtxtCorreoMedico.equals("")){       
            
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
          
    }else{
        try{
            PreparedStatement crear = conect.prepareStatement("insert into usuario_medico (usuario_medico, contraseña_medico, nombres_medico, apellidos_medico, sede, celular_medico, especialidad_medico, correo_medico) values(?,?,?,?,?,?,?,?);");
            
             if(contrme.equals(contrconfme) ) {
                crear.setString(1,jtxtUsuarioMedico.getText());
                crear.setString(2,jtxtContraseñaMedico.getText());
                crear.setString(3,jtxtNombresMedico.getText());
                crear.setString(4,jtxtApellidosMedico.getText());
                crear.setString(5,jtxtSedeMedico.getText());
                crear.setString(6,jtxtCelularMedico.getText());
                crear.setString(7,jtxtEspecializacionMedico.getText());
                crear.setString(8,jtxtCorreoMedico.getText()); 
                crear.executeUpdate();
                JOptionPane.showMessageDialog(null,"REGISTRO COMPLETADO");
                jtxtUsuarioMedico.setText("");
                jtxtContraseñaMedico.setText("");
                jtxtReContraseñaMedico.setText("");
                jtxtNombresMedico.setText("");
                jtxtApellidosMedico.setText("");
                jtxtSedeMedico.setText("");
                jtxtCelularMedico.setText("");
                jtxtEspecializacionMedico.setText("");
                jtxtCorreoMedico.setText(""); 
             }else{
                 JOptionPane.showMessageDialog(null,"LAS CONTRASEÑAS NO COINCIDEN");
             }
             
                          
                          
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,e +"NO SE COMLETO EL REGISTRO");
       
     }
        
        }   
    }//GEN-LAST:event_jbtnCrearMedicoActionPerformed

    private void jbtxActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtxActualizarActionPerformed
                 lecturadatos();
                ActualizarDoc(doc);
                
                
    }//GEN-LAST:event_jbtxActualizarActionPerformed

    private void jbtxBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtxBuscarActionPerformed
        Doctor doc = null;
             id = JOptionPane.showInputDialog("Ingrese el usuario a buscar....");            
            Statement st;// realizar el espaciado para realizar la consulta
            ResultSet rs;// despues de la consulta tiene los registros     
               
            
            try{
            st = conect.createStatement();// crea espacion para ejecutar la consulta
            //ejecutamos la consulta, cocatenando el codigo a buscar
            rs = st.executeQuery("select * from usuario_medico where usuario_medico='"+id+"';");
            if(rs.next()){ //ve si hat 1 registro
                doc = new Doctor();//creamos un objeto
                doc.setUsuario_medico(rs.getString(2));//recuperamos el codigo
                doc.setContraseña_medico(rs.getString(3));//recuperamos el nombre
                doc.setNombres_medico(rs.getString(4));//recuperamos la direccion
                doc.setApellidos_medico(rs.getString(5));//recuperamos la carrera
                doc.setSede(rs.getString(6));//recuperamos la carrera
                doc.setCelular_medico(rs.getString(7));//recuperamos la carrera
                doc.setEspecialidad_medico(rs.getString(8));//recuperamos la carrera
                doc.setCorreo_medico(rs.getString(9));//recuperamos la carrera
                
            }
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"ERROR al consultar medico..."+e);
        }
        
             if(doc  == null){
                JOptionPane.showMessageDialog(null,"El codigo "+id+" no existe en la colección");
             } else{
                      
                    jtxtUsuarioMedico.setText(doc.getUsuario_medico());
                    jtxtContraseñaMedico.setText(doc.getContraseña_medico());
                    jtxtReContraseñaMedico.setText(doc.getContraseña_medico());
                    jtxtNombresMedico.setText(doc.getNombres_medico());
                    jtxtApellidosMedico.setText(doc.getApellidos_medico());
                    jtxtSedeMedico.setText(doc.getSede());
                    jtxtCelularMedico.setText(doc.getCelular_medico());
                    jtxtEspecializacionMedico.setText(doc.getEspecialidad_medico());
                    jtxtCorreoMedico.setText(doc.getCorreo_medico()); 
                                     
                      }
        
        
        
        
        
    }//GEN-LAST:event_jbtxBuscarActionPerformed

    private void jbtxEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtxEliminarActionPerformed
        int respuesta = JOptionPane.showConfirmDialog(null, 
                "Esta seguro de eliminar el registro?", "Confirmación...",JOptionPane.YES_NO_CANCEL_OPTION);
           // 0=yes, 1=no, 2=cancel
           if(respuesta == 0){
        lecturadatos();
        EliminarDoc(id);
    }//GEN-LAST:event_jbtxEliminarActionPerformed
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmRegistrar_user_medic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmRegistrar_user_medic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmRegistrar_user_medic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmRegistrar_user_medic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmRegistrar_user_medic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton jbtnCrearMedico;
    private javax.swing.JButton jbtxActualizar;
    private javax.swing.JButton jbtxBuscar;
    private javax.swing.JButton jbtxEliminar;
    public javax.swing.JTextField jtxtApellidosMedico;
    public javax.swing.JTextField jtxtCelularMedico;
    public javax.swing.JPasswordField jtxtContraseñaMedico;
    public javax.swing.JTextField jtxtCorreoMedico;
    public javax.swing.JTextField jtxtEspecializacionMedico;
    public javax.swing.JTextField jtxtNombresMedico;
    public javax.swing.JPasswordField jtxtReContraseñaMedico;
    public javax.swing.JTextField jtxtSedeMedico;
    public javax.swing.JTextField jtxtUsuarioMedico;
    // End of variables declaration//GEN-END:variables
}
