
package Vistas;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import DAO.*;


public class jfrm_lista_medico extends javax.swing.JFrame {
    
   
    conexion_medico enlace = new conexion_medico();
    Connection conect = enlace.conexion_medico(); 
    
    public jfrm_lista_medico() {
        initComponents();
        mostrarDatosdoctor ();
        
    }
    
    public void mostrarDatosdoctor () {
     DefaultTableModel tmedico = new DefaultTableModel ();
    tmedico.addColumn ("ID");
    tmedico.addColumn ("USUARIO");
    tmedico.addColumn ("CONTRASEÑA");
    tmedico.addColumn ("NOMBRE");
    tmedico.addColumn ("APELLIDOS");    
    tmedico.addColumn ("SEDE");
    tmedico.addColumn ("TELÉFONO");
    tmedico.addColumn ("ESPECIALIDAD");
    tmedico.addColumn ("CORREO");
    tmedico.addColumn ("FECHA DE REGISTRO");
    tmedico.addColumn ("TIPO ID");
    jtblListaMedico.setModel(tmedico);
    
    String []datos = new String[11];
    try {
      Statement leer = conect.createStatement();
       ResultSet resultado = leer.executeQuery("SELECT * FROM usuario_medico");
      while (resultado.next ()){
        datos[0] = resultado.getString(1);
        datos[1] = resultado.getString(2);
        datos[2] = resultado.getString(3);
        datos[3] = resultado.getString(4);
        datos[4] = resultado.getString(5);
        datos[5] = resultado.getString(6);
        datos[6] = resultado.getString(7);
        datos[7] = resultado.getString(8);
        datos[8] = resultado.getString(9);
        datos[9] = resultado.getString(10);
        datos[10] = resultado.getString(11);
        tmedico.addRow (datos);
        }
        jtblListaMedico.setModel (tmedico);
        
      } catch (Exception e) {
        JOptionPane.showMessageDialog (null,"Error en la consulta");
      }
    }      

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblListaMedico = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LISTA REGISTRO DE MEDICOS");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jtblListaMedico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jtblListaMedico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblListaMedico);

        jPanel1.add(jScrollPane1);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 1040, 580));

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setText("CERRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 620, 140, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
            
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrm_lista_medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrm_lista_medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrm_lista_medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrm_lista_medico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrm_lista_medico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jtblListaMedico;
    // End of variables declaration//GEN-END:variables
}
