/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Modelos.forddental;
import Modelos.hs;
import Modelos.sqlforddental_pa;
import static Vistas.Iniciar.registrarpa;
import javax.swing.JOptionPane;

/**
 *
 * @author aless
 */
public class jfrmRegistrar_user_pacie extends javax.swing.JFrame {

    /**
     * Creates new form jfrmRegistrar_user_pacie
     */
    public jfrmRegistrar_user_pacie() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtUsuarioPaciente = new javax.swing.JTextField();
        jtxtContraseñaPaciente = new javax.swing.JPasswordField();
        jtxtReContraseñaPaciente = new javax.swing.JPasswordField();
        jtxtNombresPaciente = new javax.swing.JTextField();
        jtxtApellidosPaciente = new javax.swing.JTextField();
        jtxtCorreoPaciente = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jtxtTelefonoPaciente = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jbtnCrearPaciente = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(0, 102, 102));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USUARIO:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 55, 71, 22));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CONTRASEÑA: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 119, 101, 28));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("<html>REPETIR CONTRASEÑA:</html>");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 110, 40));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NOMBRES:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 100, 30));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("APELLIDOS:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, 80, 22));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("CORREO:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, 70, 27));

        jtxtUsuarioPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUsuarioPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtUsuarioPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 190, 30));
        jPanel1.add(jtxtContraseñaPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 122, 190, 30));
        jPanel1.add(jtxtReContraseñaPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 190, 30));

        jtxtNombresPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNombresPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtNombresPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 220, 190, 30));
        jPanel1.add(jtxtApellidosPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 270, 190, 30));
        jPanel1.add(jtxtCorreoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 320, 190, 30));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("TELEFONO:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 80, 30));
        jPanel1.add(jtxtTelefonoPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 190, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CREAR USUARIO PACIENTE");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 0, 270, 49));

        jbtnCrearPaciente.setBackground(new java.awt.Color(255, 255, 255));
        jbtnCrearPaciente.setText("CREAR");
        jbtnCrearPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnCrearPacienteActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnCrearPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 430, 165, 44));

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("(USAR NRO DE DNI)");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtNombresPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNombresPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombresPacienteActionPerformed

    private void jbtnCrearPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnCrearPacienteActionPerformed
        sqlforddental_pa msql= new sqlforddental_pa();
        forddental mford=new forddental();
        
        String contr = new String(jtxtContraseñaPaciente.getPassword());
        String contrconf = new String(jtxtReContraseñaPaciente.getPassword());
        
        if (jtxtUsuarioPaciente.getText().equals("") || contr.equals("") || contrconf.equals("") || 
                jtxtNombresPaciente.equals("") || jtxtApellidosPaciente.equals("") || jtxtCorreoPaciente.equals("") || jtxtTelefonoPaciente.equals("")){       
            
            JOptionPane.showMessageDialog(null, "Debes llenar todos los campos");
    }else{
        if(contr.equals(contrconf)){ 
            if(msql.UsuarioExistente(jtxtUsuarioPaciente.getText())==0){                
            
                
            String newpass = hs.sha1(contr);
            mford.setUsuario(jtxtUsuarioPaciente.getText());
            mford.setContraseña(newpass);
            mford.setNombres(jtxtNombresPaciente.getText());
            mford.setApellidos(jtxtApellidosPaciente.getText());
            mford.setCorreo(jtxtCorreoPaciente.getText());
            mford.setTelefono(jtxtTelefonoPaciente.getText());
            mford.setId_tipo(1);
            if(msql.registrar(mford)){
                JOptionPane.showMessageDialog(null, "GUARDADO CORRECTAMENTE");                
            }else{
                JOptionPane.showMessageDialog(null, "SE HA GENERADO UN ERROR");
            }
            }else{
                JOptionPane.showMessageDialog(null, "Usuario existente");
            }
        }else{
            JOptionPane.showMessageDialog(null, "ES INCORRECTO");
        }
     }
    }//GEN-LAST:event_jbtnCrearPacienteActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Iniciar.registrarpa = null;
    }//GEN-LAST:event_formWindowClosing

    private void jtxtUsuarioPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUsuarioPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtUsuarioPacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrmRegistrar_user_pacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrmRegistrar_user_pacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrmRegistrar_user_pacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrmRegistrar_user_pacie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrmRegistrar_user_pacie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnCrearPaciente;
    private javax.swing.JTextField jtxtApellidosPaciente;
    private javax.swing.JPasswordField jtxtContraseñaPaciente;
    private javax.swing.JTextField jtxtCorreoPaciente;
    private javax.swing.JTextField jtxtNombresPaciente;
    private javax.swing.JPasswordField jtxtReContraseñaPaciente;
    private javax.swing.JTextField jtxtTelefonoPaciente;
    private javax.swing.JTextField jtxtUsuarioPaciente;
    // End of variables declaration//GEN-END:variables
}
