/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import Modelos.forddental;
import Modelos.hs;
import Vistas.JfrmCitas;
import Modelos.sqlforddental_pa;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import static java.util.Objects.hash;
import javax.swing.JOptionPane;

/**
 *
 * @author aless
 */
public class login_pacientes extends javax.swing.JFrame {

    /**
     * Creates new form login
     */
    public login_pacientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtUsuarioPa = new javax.swing.JTextField();
        jtxtContraseñaPa = new javax.swing.JPasswordField();
        jbtnIngresarPa = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("USUARIO:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, 20));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CONTRASEÑA:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, -1, 20));

        jtxtUsuarioPa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtUsuarioPaActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtUsuarioPa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 140, 30));
        jPanel1.add(jtxtContraseñaPa, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 140, 30));

        jbtnIngresarPa.setBackground(new java.awt.Color(255, 255, 255));
        jbtnIngresarPa.setText("INGRESAR");
        jbtnIngresarPa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIngresarPaActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnIngresarPa, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 390, 160, 50));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("INICIAR SESION PACIENTE");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 260, 40));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/imag9.jpg"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 210, 210));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtUsuarioPaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtUsuarioPaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtUsuarioPaActionPerformed

    private void jbtnIngresarPaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIngresarPaActionPerformed
        sqlforddental_pa pasql = new sqlforddental_pa();
        forddental pa = new forddental();                        
        String pass = new String(jtxtContraseñaPa.getPassword());
        if(!jtxtUsuarioPa.getText().equals("") && !pass.equals("")){
            String newpass = hs.sha1(pass);
            pa.setUsuario(jtxtUsuarioPa.getText());
            pa.setContraseña(newpass);
                        
            if(pasql.LOGIN(pa)){ 
                Iniciar.loginpa = null;
                this.dispose();
                JfrmCitas frmCitas= new JfrmCitas();
                frmCitas.setVisible(true);
                
            }else{
                JOptionPane.showMessageDialog(null, "Los datos son incorrectos");
            }                
        }else{
            JOptionPane.showMessageDialog(null, "ERROR, INGRESE SUS DATOS");
        }
        
    }//GEN-LAST:event_jbtnIngresarPaActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        Iniciar.loginpa = null;
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login_pacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login_pacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login_pacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login_pacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login_pacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnIngresarPa;
    private javax.swing.JPasswordField jtxtContraseñaPa;
    private javax.swing.JTextField jtxtUsuarioPa;
    // End of variables declaration//GEN-END:variables
}
