package Vistas;

import DAO.Conexion;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author K
 */
public class PagosRecepcion extends javax.swing.JFrame {
    Conexion cn= new Conexion();
    Connection con=cn.getConexion();
    public PagosRecepcion() {
        initComponents();
        mostrarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtCodigopagoRCP = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jbtnGuardarpagoRCP = new javax.swing.JButton();
        jbtnModificarpagoRCP = new javax.swing.JButton();
        jtxtDNIpagoRCP = new javax.swing.JTextField();
        jtxtEspecialidadpagoRCP = new javax.swing.JTextField();
        jtxtMontopagoRCP = new javax.swing.JTextField();
        jbtnEliminarpagoRCP = new javax.swing.JButton();
        jdcFechapagoRCP = new com.toedter.calendar.JDateChooser();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblListapagoRCP = new javax.swing.JTable();
        jtxtBusquedaRCP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "REGISTRO DE PAGOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Codigo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 100, 40));
        jPanel1.add(jtxtCodigopagoRCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 30, 190, 50));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Fecha de pago");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 110, 50));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("DNI");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 60, 50));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Especialidad");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 100, 50));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Monto");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 90, 50));

        jbtnGuardarpagoRCP.setBackground(new java.awt.Color(255, 255, 255));
        jbtnGuardarpagoRCP.setText("GUARDAR");
        jbtnGuardarpagoRCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardarpagoRCPActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnGuardarpagoRCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 150, 50));

        jbtnModificarpagoRCP.setBackground(new java.awt.Color(255, 255, 255));
        jbtnModificarpagoRCP.setText("MODIFICAR");
        jbtnModificarpagoRCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnModificarpagoRCPActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnModificarpagoRCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 500, 150, 50));
        jPanel1.add(jtxtDNIpagoRCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 190, 50));
        jPanel1.add(jtxtEspecialidadpagoRCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 190, 50));
        jPanel1.add(jtxtMontopagoRCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 300, 190, 50));

        jbtnEliminarpagoRCP.setBackground(new java.awt.Color(255, 255, 255));
        jbtnEliminarpagoRCP.setText("ELIMINAR");
        jbtnEliminarpagoRCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnEliminarpagoRCPActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnEliminarpagoRCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 500, 140, 50));

        jdcFechapagoRCP.setDateFormatString("yyyy/MM/dd HH:mm:ss");
        jPanel1.add(jdcFechapagoRCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(148, 100, 190, 50));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 570));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LISTADO DE PAGOS", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 14))); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtblListapagoRCP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jtblListapagoRCP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtblListapagoRCPMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtblListapagoRCP);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 730, 450));

        jtxtBusquedaRCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBusquedaRCPActionPerformed(evt);
            }
        });
        jtxtBusquedaRCP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtxtBusquedaRCPKeyReleased(evt);
            }
        });
        jPanel2.add(jtxtBusquedaRCP, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 180, 40));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Busqueda");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 160, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 0, 750, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnEliminarpagoRCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnEliminarpagoRCPActionPerformed
        eliminarRegistros();
        limpiarDatos();
        mostrarDatos();
    }//GEN-LAST:event_jbtnEliminarpagoRCPActionPerformed

    private void jbtnGuardarpagoRCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarpagoRCPActionPerformed
        insertarDatos();
        limpiarDatos();
        mostrarDatos();
    }//GEN-LAST:event_jbtnGuardarpagoRCPActionPerformed

    private void jtblListapagoRCPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtblListapagoRCPMouseClicked
        int filaSeleccionada=jtblListapagoRCP.rowAtPoint(evt.getPoint());
        
        jtxtCodigopagoRCP.setText(jtblListapagoRCP.getValueAt(filaSeleccionada, 1).toString());
        jdcFechapagoRCP.setToolTipText(jtblListapagoRCP.getValueAt(filaSeleccionada, 2).toString());
        jtxtDNIpagoRCP.setText(jtblListapagoRCP.getValueAt(filaSeleccionada, 3).toString());
        jtxtEspecialidadpagoRCP.setText(jtblListapagoRCP.getValueAt(filaSeleccionada, 4).toString());
        jtxtMontopagoRCP.setText(jtblListapagoRCP.getValueAt(filaSeleccionada, 5).toString());
        
        
    }//GEN-LAST:event_jtblListapagoRCPMouseClicked

    private void jbtnModificarpagoRCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnModificarpagoRCPActionPerformed
        actualizarDatos();
        limpiarDatos();
        mostrarDatos();
    }//GEN-LAST:event_jbtnModificarpagoRCPActionPerformed

    private void jtxtBusquedaRCPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtxtBusquedaRCPKeyReleased
        filtrarDatos(jtxtBusquedaRCP.getText());
    }//GEN-LAST:event_jtxtBusquedaRCPKeyReleased

    private void jtxtBusquedaRCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBusquedaRCPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtBusquedaRCPActionPerformed
    public void insertarDatos(){
        try{
            String sql="insert into pago_recepcion (codigo_pagorecepcion,fecha_pagorecepcion,dni_pagorecepcion,especialidad_pagorecepcion,monto_pagorecepcion) values (?,?,?,?,?)";
            PreparedStatement pst=con.prepareStatement(sql);
            
            pst.setString(1, jtxtCodigopagoRCP.getText());
            pst.setString(2, ((JTextField)jdcFechapagoRCP.getDateEditor().getUiComponent()).getText());
            pst.setString(3, jtxtDNIpagoRCP.getText());
            pst.setString(4, jtxtEspecialidadpagoRCP.getText());
            pst.setDouble(5, Double.parseDouble(jtxtMontopagoRCP.getText()));
            pst.execute();
            JOptionPane.showMessageDialog(null,"Registrado");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error de registro");
        }
    }
    public void actualizarDatos(){
        try{
            String sql=" update pago_recepcion set codigo_pagorecepcion=?,fecha_pagorecepcion=?,dni_pagorecepcion=?,especialidad_pagorecepcion=?,monto_pagorecepcion=? where id_pagorecepcion=? ";
            int filaseleccionado=jtblListapagoRCP.getSelectedRow();
            String dao=(String)jtblListapagoRCP.getValueAt(filaseleccionado, 0);
            PreparedStatement pst=con.prepareStatement(sql);
            
            pst.setString(1, jtxtCodigopagoRCP.getText());
            pst.setString(2, ((JTextField)jdcFechapagoRCP.getDateEditor().getUiComponent()).getText());
            pst.setString(3, jtxtDNIpagoRCP.getText());
            pst.setString(4, jtxtEspecialidadpagoRCP.getText());
            pst.setDouble(5, Double.parseDouble(jtxtMontopagoRCP.getText()));
            pst.setString(6, dao);
            pst.execute();
            JOptionPane.showMessageDialog(null,"Registrado Actualizado");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error al Actualizar");
        }
    }
    public void eliminarRegistros(){
        int filaSeleccionada=jtblListapagoRCP.getSelectedRow();
        try{
            String sql="delete from pago_recepcion where id_pagorecepcion="+jtblListapagoRCP.getValueAt(filaSeleccionada, 0);
            Statement st=con.createStatement();
            int n=st.executeUpdate(sql);
            if(n>=0){
                JOptionPane.showMessageDialog(null,"Registro Eliminado");
            } 
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error al eliminar Registro");
        }
    }
    public void limpiarDatos(){
        jtxtCodigopagoRCP.setText("");
        jdcFechapagoRCP.setToolTipText("");
        jtxtDNIpagoRCP.setText("");
        jtxtEspecialidadpagoRCP.setText("");
        jtxtMontopagoRCP.setText("");
        
    }
    public void mostrarDatos(){
        String[] titulos={"Id","Codigo","Fecha","DNI","Especialidad","Monto"};
        String[] registros=new String[6];
        
        DefaultTableModel model=new DefaultTableModel(null,titulos);
        
        String sql="select * from pago_recepcion";
        
        try{
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
                registros[0]=rs.getString("id_pagorecepcion");
                registros[1]=rs.getString("codigo_pagorecepcion");
                registros[2]=rs.getString("fecha_pagorecepcion");
                registros[3]=rs.getString("dni_pagorecepcion");
                registros[4]=rs.getString("especialidad_pagorecepcion");
                registros[5]=rs.getString("monto_pagorecepcion");
                
                model.addRow(registros);
            }
            jtblListapagoRCP.setModel(model);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error al mostrar datos");
        }
    }
    
    public void filtrarDatos(String valor){
        String[] titulos={"Id","Codigo","Fecha","DNI","Especialidad","Monto"};
        String[] registros=new String[6];
        
        DefaultTableModel model=new DefaultTableModel(null,titulos);
        
        String sql="select * from pago_recepcion where codigo_pagorecepcion like '%"+valor+"%'";
        
        try{
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(sql);
            while(rs.next()){
                registros[0]=rs.getString("id_pagorecepcion");
                registros[1]=rs.getString("codigo_pagorecepcion");
                registros[2]=rs.getString("fecha_pagorecepcion");
                registros[3]=rs.getString("dni_pagorecepcion");
                registros[4]=rs.getString("especialidad_pagorecepcion");
                registros[5]=rs.getString("monto_pagorecepcion");
                
                model.addRow(registros);
            }
            jtblListapagoRCP.setModel(model);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Error al mostrar datos");
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagosRecepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagosRecepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagosRecepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagosRecepcion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagosRecepcion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbtnEliminarpagoRCP;
    private javax.swing.JButton jbtnGuardarpagoRCP;
    private javax.swing.JButton jbtnModificarpagoRCP;
    private com.toedter.calendar.JDateChooser jdcFechapagoRCP;
    private javax.swing.JTable jtblListapagoRCP;
    private javax.swing.JTextField jtxtBusquedaRCP;
    private javax.swing.JTextField jtxtCodigopagoRCP;
    private javax.swing.JTextField jtxtDNIpagoRCP;
    private javax.swing.JTextField jtxtEspecialidadpagoRCP;
    private javax.swing.JTextField jtxtMontopagoRCP;
    // End of variables declaration//GEN-END:variables
}
