package Modelos;
public interface Precios {
    //ODOLONTOLOGIA INTEGRAL
    double CUNA_DISTAL=60;
    double DESTARTRAJE_ULTRASONIDO=100;
    double REPARACION_PERFORACIONES=180;
    double PROFILAXIS=33;
    double SELLANTES_PIEZAS=23;
    double FISIOTERAPIA_ORAL=11;
    double OBTURACION_RESINA_1SUP=41;
    double OBTURACION_RESINA_2SUP=56;
    double OBTURACION_RESINA_3SUP=74;
    //RADIOLOGIA
    double RADIOGRAFIA_PERIAPICAL=10;
    double RADIOGRAFIA_PANORAMICA=35;
    //ODONTOPEDIATRIA
    double FLUOR_GEL_ARCADA=30;
    double PULPOTOMIA=69;
    //PERIODONCIA
    double COLGAJO_PERIODONTAL=360;
    double GINGIVECTOMIAS=141;
    double INJERTO_OSEO=200;
    double IMPLANTES_DENTALES=2980;
    double REIMPLANTE_DENTARIO=60;
    double REMOCION_CALCULOS_SUPRAGING=57;
    double REMODELADO_OSEO=160;
    //CIRUGIA
    double ALARGAMIENTO_CORONA=180;
    double ALARGAMIENTO_CORONA_OSTEOMIA=187;
    double CIRUGIA_METODO_ABIERTO=233;
    double CIRUGIA_MUCOGINGIVAL=180;
    double EXODONCIA_TEMPORAL=30;
    double EXODONCIA_SIMPLE=40;
    double FRENECTOMIA=176;
    double ESCISION_TORUS=150;
    //ENDODONCIA
    double APEXOGENESIS=80;
    double APICECTOMIA_ANTERIORES=250;
    double APICECTOMIA_POSTERIORES=300;
    double ENDODONCIA_ANTERIOR=158;
    double ENDODONCIA_ANTERIOR_TEMPORAL=69;
    double ENDODONCIA_POSTERIOR_TEMPORAL=69;
    double ENDODONCIA_MOLARES=246;
    double ENDODONCIA_PREMOLARES=189;
    //ODOLONTOLOGIA ESTETICA
    double BLANQUEAMIENTO_CASERO=318;
    double BLANQUEAMIENTO_LUZ=400;
    double BLANQUEAMIENTO_DIENTE=100;
    double CARILLA_RESINA=193;
    double CARILLA_RESINA_TEMPORAL=70;
    //REHABILITACION ORAL
    double CARILLA_PORCELANA=734;
    double CORONA_ACRILICO_TERMOCURADO=112;
    double INCRUSTACION_METAL=216;
    double INCRUSTACION_PORCELANA=613;
    double PERNO_MUNON_COLADO=183;
    double PLACA_MIORRELAJANTE=254;
    double PPR_ACRILICO=510;
    double PROTESIS_TOTAL_DIENTES=693;
    double REPARACION_PROTESIS=88;
    //ORTODONCIA
    double ORTODONCIA_CORRECTIVA=180;
    double MANTENEDOR_ESPACIO=260;
    double PAQUETE_ORTODONCIA=155;
    double TRATAMIENTO_BRACKETS_1=318;
    double TRATAMIENTO_BRACKETS_2=272;
    double TRATAMIENTO_BRACKETS_3=249;
}
